services:
  umetaflow-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: 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
    image: umetaflow_app
    container_name: umetaflow-app
    restart: always
    ports:
      - 8501:8501
    volumes:
      - workspaces-umetaflow-gui:/workspaces-umetaflow-gui
    command: streamlit run umetaflow-gui/app.py
volumes:
  workspaces-umetaflow-gui:
