name: umetaflow-gui
channels:
  - conda-forge
dependencies:
  - python=3.11
  - plotly
  - pip
  - numpy
  - pandas
  - mono
  - pip: # dependencies only available through pip
      # streamlit dependencies
    - streamlit
    - streamlit-plotly-events
    - streamlit-aggrid
    - pyopenms
    - pyteomics
    - scikit-learn
    - scipy
    - captcha
